CC = cl
CFLAGS = /nologo /W3 /D_CRT_SECURE_NO_WARNINGS
LIBS = kernel32.lib user32.lib

all: master_controller.exe trainer.exe arena.exe

master_controller.exe: master_controller.c shared_memory.c
	$(CC) $(CFLAGS) master_controller.c shared_memory.c /Fe$@ $(LIBS)

trainer.exe: trainer.c shared_memory.c
	$(CC) $(CFLAGS) trainer.c shared_memory.c /Fe$@ $(LIBS)

arena.exe: arena.c shared_memory.c
	$(CC) $(CFLAGS) arena.c shared_memory.c /Fe$@ $(LIBS)

clean:
	del *.exe *.obj

run: all
	.\master_controller.exe